import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.scss";
import AppRoutes from "./AppRoutes";
import { Inter } from 'next/font/google';
import '@fontsource/inter/600.css';

const inter = Inter({
  subsets: ['latin'],
  weight: '600',
  variable: '--font-inter',
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${inter.variable} ${geistSans.variable} ${geistMono.variable}`}>
      <body
        className="antialiased"
        suppressHydrationWarning // ✅ Fixes hydration mismatch from browser extensions
      >
        {/* ✅ Only render AppRoutes - remove {children} */}
        <AppRoutes />
      </body>
    </html>
  );
}